# Generated by Django 5.0.4 on 2024-05-05 09:25

import django.core.validators
import purchase_order.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True, validators=[purchase_order.helper.validate_acknowledgment_date]),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='delivery_date',
            field=models.DateTimeField(validators=[purchase_order.helper.validate_delivery_date]),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='items',
            field=models.JSONField(validators=[purchase_order.helper.validate_items]),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='quality_rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
